name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1        
#      - name: Deploy UserService
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "user-service-13062022-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}
#
#      - name: Deploy Account Service
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "bike-rental-account-service-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}

#      - name: Deploy BikeService
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "bike-service-13062022-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}
#
#      - name: Deploy Bike Booking Service
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "bike-rental-booking-service-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}
#
      - name: Deploy Notification Service
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bike-rental-notification-1"
          heroku_email: ${{secrets.HEROKU_API_KEY}}
#
#      - name: Deploy Payment Service
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "bike-rental-payment-service-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}

#      - name: Deploy Aggregator
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "api-gateway-agg-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}

#      - name: Deploy API Gateway
#        uses: akhileshns/heroku-deploy@v3.0.4
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "bike-rental-api-gateway-1"
#          heroku_email: ${{secrets.HEROKU_API_KEY}}
